import { FormEvent, useState } from 'react';
import { ArrowLeft, ArrowRight, Building2, Check, Stethoscope, UserCog } from 'lucide-react';
import { native } from '../../services/native';

type Setup = { clinicName:string; address:string; phone:string; dentistName:string; username:string; password:string; confirm:string; autoLockMinutes:number };
const initial: Setup={clinicName:'',address:'',phone:'',dentistName:'',username:'',password:'',confirm:'',autoLockMinutes:10};
const labels=['Clinic identity','Dentist','Administrator']; const icons=[Building2,Stethoscope,UserCog];

export function SetupWizard({onComplete}:{onComplete:()=>Promise<void>}) {
 const [step,setStep]=useState(0); const [form,setForm]=useState(initial); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 const set=(key:keyof Setup,value:string|number)=>setForm(current=>({...current,[key]:value}));
 const next=(event:FormEvent)=>{event.preventDefault();setError('');if(step===0&&!form.clinicName.trim())return setError('Clinic name is required.');if(step===1&&!form.dentistName.trim())return setError('At least one dentist is required.');setStep(value=>Math.min(2,value+1));};
 const finish=async(event:FormEvent)=>{event.preventDefault();setError('');if(form.username.trim().length<3)return setError('Username must have at least 3 characters.');if(form.password.length<10)return setError('Use at least 10 characters for the administrator password.');if(form.password!==form.confirm)return setError('Passwords do not match.');setBusy(true);try{await native.completeSetup({...form});await onComplete();}catch(reason){const value=reason as {message?:string};setError(value.message??'Setup could not be saved. Please review the information and try again.');}finally{setBusy(false)}};
 const submit=step===2?finish:next;
 return <main className="setup-shell"><header><div className="setup-brand"><span className="brand-mark"><Building2/></span><span><strong>Dentiva Pro</strong><small>Initial clinic setup</small></span></div><span className="secure-label">Saved locally on this computer</span></header><div className="setup-layout"><aside><p className="eyebrow">Getting started</p><h1>Let’s prepare your practice.</h1><p>Three short steps create the protected workspace. You can add more details and dentists later.</p><ol>{labels.map((label,index)=>{const Icon=icons[index];return <li key={label} className={index===step?'active':index<step?'complete':''}><span>{index<step?<Check/>:<Icon/>}</span><div><small>Step {index+1}</small><strong>{label}</strong></div></li>})}</ol></aside><section className="setup-form"><div className="step-count">Step {step+1} of 3</div><p className="eyebrow">{labels[step]}</p><h2>{step===0?'Tell us about your clinic':step===1?'Add the primary dentist':'Protect the administrator account'}</h2><p className="lead">{step===0?'This identity appears throughout Dentiva Pro and on printed documents.':step===1?'Every clinical record will preserve the responsible dentist.':'Use this account to configure staff roles, security and backups.'}</p>
 <form onSubmit={submit} noValidate>{step===0&&<><Field label="Dental Clinic / Dental Care Name" value={form.clinicName} set={v=>set('clinicName',v)} required autoFocus/><Field label="Address" value={form.address} set={v=>set('address',v)}/><Field label="Phone" value={form.phone} set={v=>set('phone',v)}/><div className="field-row"><div><label>Default currency</label><input value="BDT — ৳" disabled/></div><div><label>Timezone</label><input value="Asia/Dhaka" disabled/></div></div></>}{step===1&&<><Field label="Dentist full name" value={form.dentistName} set={v=>set('dentistName',v)} required autoFocus/><div className="notice">The dentist starts with code <strong>DR-001</strong>. Degrees, designations, registration and availability can be completed in Dentist Settings.</div></>}{step===2&&<><Field label="Administrator username" value={form.username} set={v=>set('username',v)} required autoFocus/><Field label="Password" type="password" value={form.password} set={v=>set('password',v)} required/><Field label="Confirm password" type="password" value={form.confirm} set={v=>set('confirm',v)} required/><label htmlFor="timeout">Auto-lock after inactivity</label><select id="timeout" value={form.autoLockMinutes} onChange={e=>set('autoLockMinutes',Number(e.target.value))}>{[5,10,15,30].map(v=><option key={v} value={v}>{v} minutes</option>)}<option value={0}>Disabled</option></select></>}{error&&<p className="field-error" role="alert">{error}</p>}<div className="form-actions">{step>0&&<button type="button" className="button secondary" onClick={()=>{setError('');setStep(v=>v-1)}}><ArrowLeft/>Back</button>}<button className="button primary" disabled={busy}>{busy?'Creating workspace…':step===2?<>Complete setup <Check/></>:<>Continue <ArrowRight/></>}</button></div></form></section></div></main>
}
function Field({label,value,set,type='text',required=false,autoFocus=false}:{label:string;value:string;set:(v:string)=>void;type?:string;required?:boolean;autoFocus?:boolean}) {const id=label.toLowerCase().replace(/\W/g,'-');return <><label htmlFor={id}>{label}{required&&<span aria-hidden="true"> *</span>}</label><input id={id} type={type} value={value} onChange={e=>set(e.target.value)} required={required} autoFocus={autoFocus} autoComplete={type==='password'?'new-password':'off'}/></>}
